### ISSUE TITLE
道路中心線：IDの命名規則と，リンクの区間の決め方について

### ISSUE THREAD

**Issue by tosseto** [gsi-cyberjapan/experimental_rdcl#1]
地図情報（道路中心線）についてお尋ねします．

サンプルデータのGeoJSONや地理院地図でのベクトルタイルの可視化事例を拝見すると，レコードIDとして，例えば「50382-12852-i-1410」というIDが振られていますが，IDの命名規則（各ハイフンの数字ごとの意味するところなど）が決まっていれば教えて頂けますでしょうか．

関連して，電子国土基本図地図情報ファイル仕様書についても参照したところ，「区間ID [0..1] : CharacterString 道路の区間を識別するための区間ID。」に相当するのかとも思い至りましたが，確証がなくご教示頂けると幸いです．

また，道路リンクの各区間のデータの生成方法ですが，必ずしもノード（ラインとラインの結節点）が，交差点に打たれているとは限らないようですが，これについても規則性などあれば教えて下さい．

**Comment by johofukyu** [comment]
お問合せいただきありがとうございます。
この度はご返信が遅くなってしまい、申し訳ありません。

レコードIDについては、管理用のユニークなIDを任意に付与しているものです。
（参考）電子国土基本図地図情報ファイル仕様書
https://www.gsi.go.jp/common/000189294.pdf#page=23
なお、これらは区間IDとは異なるものです。

また、地図情報（道路中心線）のノードについては、一般に道路の交差点のほかにタイル境界や属性の変化する点にも設けられます。
以上、よろしくお願いします。

**Comment by tosseto** [comment]
どうもありがとうございました！理解できました．
